FROM golang:1.24-alpine AS builder
RUN apk add --no-cache git
WORKDIR /app
COPY ./requirements/app_consumer/go.mod ./requirements/app_consumer/go.sum ./
RUN go mod download
COPY ./requirements/app_consumer/ .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o app ./cmd

FROM scratch
COPY --from=builder /app/app /app/app
COPY --from=builder /app/internal/web /app/web
WORKDIR /app
CMD ["/app/app"]